version: '3'

services:
  db:
    container_name: db
    image: percona/percona-server:8.0.39
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3306:3306'
    volumes:
      # This auto-loads our base db and schema without 3rd party tools or scripts.
      - ./demodb.sql:/docker-entrypoint-initdb.d/1.sql

  liquibase:
    image: ekolp/liquibase:latest
    container_name: liquibase
    command: liquibase --defaults-file=/liquibase/liquibase.properties update
    environment:
      - INSTALL_MYSQL=true
      # - JAVA_OPTS='-Dliquibase.percona.options="--recursion-method=none --set-vars wait_timeout=31536000,innodb_lock_wait_timeout=31536000,lock_wait_timeout=31536000 --max-load Threads_running=80 --critical-load Threads_running=200 --alter-foreign-keys-method=auto"'
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./liquibase.properties:/liquibase/liquibase.properties
      - ./changelog.xml:/liquibase/changelog.xml
      - ./schema/:/liquibase/schema/
      - ./liquibase:/liquibase/liquibase
    links:
      - db