FROM liquibase/liquibase:4.3.4

USER root
ENV PATH=/liquibase/:$
ENV LIQUIBASE_PERCONA=4.31.0
ENV PERCONA_TOOLKIT=3.3.0
ENV MYSQL_CONNECTOR=9.3.0

RUN apt-get update && apt-get install wget perl libdbi-perl libdbd-mysql-perl libterm-readkey-perl libio-socket-ssl-perl -y

RUN wget -O /liquibase/lib/liquibase-percona-4.31.0.jar https://github.com/liquibase/liquibase-percona/releases/download/v$LIQUIBASE_PERCONA/liquibase-percona-4.31.0.jar
RUN chown 1001:1001 /liquibase/lib/liquibase-percona-4.31.0jar

RUN wget https://downloads.percona.com/downloads/percona-toolkit/3.3.0/binary/debian/buster/x86_64/percona-toolkit_3.3.0-1.buster_amd64.deb && \
    dpkg -i percona-toolkit_3.3.0-1.buster_amd64.deb

RUN wget https://cdn.mysql.com//Downloads/Connector-J/mysql-connector-j-9.3.0.tar.gz && \
    tar xvf mysql-connector-j-9.3.0.tar.gz && cp mysql-connector-j-9.3.0/mysql-connector-j-9.3.0.jar /lib/

COPY liquibase /liquibase/liquibase
RUN chown 1001:1001 /liquibase/liquibase

# USER liquibase
ENTRYPOINT ["/bin/bash"]
