version: '3'

services:
  db:
    container_name: db
    image: percona/percona-server:8.0.39
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3306:3306'
    volumes:
      # This auto-loads our base db and schema without 3rd party tools or scripts.
      - ./demodb.sql:/docker-entrypoint-initdb.d/1.sql

  dbreference:
    container_name: dbreference
    image: percona/percona-server:8.0.39
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3307:3306'
    volumes:
      # This auto-loads our base db and schema without 3rd party tools or scripts.
      - ./demodb.sql:/docker-entrypoint-initdb.d/1.sql

  # liquibase:
  #   image: ekolp/liquibase
  #   container_name: liquibase
  #   entrypoint:
  #     - /bin/bash
  #   tty: true
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile-liquibase
  #   volumes:
  #     - ./:/wd
  #   working_dir: /wd
  #   links:
  #     - db

  liquibase:
    image: liquibase/liquibase:4.31.1
    container_name: liquibase
    command: --defaults-file=/wd/liquibase.properties update
    # tty: true
    environment:
      - INSTALL_MYSQL=true
    # build:
    #   context: ./
    #   dockerfile: Dockerfile-liquibase
    working_dir: /liquibase
    volumes:
      - ./liquibase.properties:/liquibase/liquibase.properties
      - ./liquibase-percona-4.31.0.jar:/liquibase/lib/liquibase-percona-4.31.0.jar
    links:
      - db
      - dbreference
