FROM liquibase/liquibase:4.3.4

USER root
ENV PATH=/liquibase/:$PATH

RUN wget -O /liquibase/lib/liquibase-percona-4.31.0.jar https://github.com/liquibase/liquibase-percona/releases/download/v4.31.0/liquibase-percona-4.31.0.jar
RUN chown 1001:1001 /liquibase/lib/liquibase-percona-4.31.0.jar

RUN apt update && apt-get install perl libdbi-perl libdbd-mysql-perl libterm-readkey-perl libio-socket-ssl-perl -y

RUN wget https://downloads.percona.com/downloads/percona-toolkit/3.3.0/binary/debian/buster/x86_64/percona-toolkit_3.3.0-1.buster_amd64.deb && \
    dpkg -i percona-toolkit_3.3.0-1.buster_amd64.deb

COPY mysql-connector-java-5.1.47.jar /lib/mysql-connector-java-5.1.47.jar

COPY liquibase /liquibase/liquibase
RUN chown 1001:1001 /liquibase/liquibase

# USER liquibase
ENTRYPOINT ["/bin/bash"]
