version: '3'

services:
  db:
    container_name: db
    image: percona/percona-server:8.0.39
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3306:3306'
    volumes:
      # This auto-loads our base db and schema without 3rd party tools or scripts.
      - ./demodb.sql:/docker-entrypoint-initdb.d/1.sql

  liquibase:
    image: ekolp/liquibase:latest
    container_name: liquibase
    command: --defaults-file=/liquibase/liquibase.properties update
    environment:
      - INSTALL_MYSQL=true
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./liquibase.properties:/liquibase/liquibase.properties
      - ./changelog.xml:/liquibase/changelog.xml
      - ./schema/:/liquibase/schema/
    links:
      - db