version: '3'

services:
  db:
    container_name: db
    image: percona/percona-server:8.0.39
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3306:3306'
    volumes:
      # This auto-loads our base db and schema without 3rd party tools or scripts.
      - ./demodb.sql:/docker-entrypoint-initdb.d/1.sql
    healthcheck:
      # Truth be told, I don't really care what this returns as long as it exits zero.
      #   I needed a startup delay on the Liquibase container so that there was ample time
      #   for the db to fully initialize. -elk
      test: bash -c "/usr/bin/netstat -ltn | grep -c 3306"
      interval: 15s
      retries: 5
      start_period: 20s # This controls the startup delay of the Liquibase container.
      timeout: 5s

  liquibase:
    image: ekolp/liquibase:latest
    container_name: liquibase
    command: --defaults-file=/liquibase/liquibase.properties update
    environment:
      - INSTALL_MYSQL=true
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./liquibase.properties:/liquibase/liquibase.properties
      - ./changelog.xml:/liquibase/changelog.xml
      - ./schema/:/liquibase/schema/
    depends_on:
      db:
        condition: service_healthy
    links:
      - db