name: Liquibase Continuous Integration

on:
  push:
    branches: [ main ]

jobs:
  ci:
    name: "Liquibase Continuous Integration Pipeline"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.15.1'

      # Run Liquibase in Two Phases so the final container exits. -elk
      - name: Run Liquibase
        id: rundbcontainer
        run: docker-compose up db -d && sleep 20

      - name: Run Liquibase
        id: runliquibase
        run: docker-compose up liquibase