name: Liquibase CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: "Continuous Integration Pipeline"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.15.1'
    
      # Install MySQL Java Connector
      - name: Install MySQL Connector
        id: runinstallmysql
        run: wget -O liquibase-percona-4.31.0.jar https://github.com/liquibase/liquibase-percona/releases/download/v4.31.0/liquibase-percona-4.31.0.jar

      # Start up demo environment
      - name: Set Up Test Env
        run: docker-compose up db -d && sleep 15

      # Run Liquibase
      - name: Run Liquibase
        id: runliquibase
        run: docker-compose up liquibase
