name: Liquibase CI

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: "us-east-1"

jobs:
  deploy:
    name: "Continuous Integration Pipeline"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # id-token: write

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.15.1' # the full version of `docker-compose` command
    
      # Start up demo environment
      - name: Set Up Test Env
        run: docker-compose up -d && sleep 15

      # Run Liquibase
      - name: Run Liquibase
        id: runliquibase
        run: docker exec liquibase liquibase update
